export const CREATE_COURSE = "CREATE_COURSE";

export const LOAD_ASSETS_SUCCESS = "LOAD_ASSESTS_SUCCESS";



export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
export const ON_TOGGLE_SUCCESS ="ON_TOGGLE_SUCCESS";
export const ON_PERCENT_ENTER_SUCCESS ="ON_PERCENT_ENTER_SUCCESS";

export const DELETE_COURSE_OPTIMISTIC = "DELETE_COURSE_OPTIMISTIC";
export const  RESET_ASSESTENTERED_SUCCESS ="RESET_ASSESTENTERED_SUCCESS";
